### ISSUE TITLE
Add docker mounted volume paths to constants.py

### ISSUE THREAD

**Issue by yaseminbridges** [monarch-initiative/pheval.exomiser#16]
When passing paths to be mounted to a docker volume, that path to which the path is being specified, e.g., `/path/to/input-data/:/exomiser-input-data` specifically `exomiser-input-data` should be specified as a constant as this is used in several places within the code.

I think what I mean here is the `TARGETDIRECTORY` which is what I want to specify in the constants so a volume I am mounting:
```
docker run -v /path/to/testdata/phenopacketdir/:TARGETDIRECTORY
```
This `TARGETDIRECTORY` is something that is required for the methods to write out the input commands for exomiser, as well as in the actual running of exomiser where I am using the `docker` package for Python to run the Exomiser docker image

**Comment by matentzn** [comment]
Ok, so this is only related to internal stuff in pheval.exomiser? As long as none of this bleeds into `pheval` its ok, because we should not have any docker specific configurations in there..

**Comment by yaseminbridges** [comment]
Yes, only for pheval.exomiser
