### ISSUE TITLE
Alter post-processing methods to reduce the occurrence of repeated code

### ISSUE THREAD

**Issue by yaseminbridges** [monarch-initiative/pheval.exomiser#4]
Dataclasses should be used to define the variables used for the pheval variant and gene results - this would avoid repetition in dataclasses and methods used to create the pheval tsv results for various plugins. 

- [ ] Define dataclasses for the bare minimum data required to produce tsv results i.e. gene/variant, score, rank
- [ ] Extract methods that can be used across plugins and move to main PhEval repo

**Comment by matentzn** [comment]
This is great! In fact most IO for the major interfaces should probably be well defined data classes! Good work!
